### ISSUE TITLE
Back up for the bots?

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOCVFinder/SOCVFinder.github.io#10]
We do face a few issues now and then, where the bots die. 

Do we need to have a backup instance for any of the bots?

**Comment by double-fault** [comment]
This seems like a good idea, especially for FireAlarm as it crashes now and then (it just crashed today). I got FireAlarm to successfully to run on my Mac, but I can't start it up right now as some needed files are with NobodyNada. I've told him to upload them.

Coincidently, the guys at Charcoal implemented a great feature like this. Smokey crashes rarely, but when it does it causes a lot of problems and someone has to start another instance. They have implemented a new "standby" feature in which two or three instances of the bot are running on different places but only one of them talks. If you run a command called `standby <location>` it puts that specific instance to standby, and `failover <location>` puts the instance specified to run.

If you're a code admin on MS (only me and Andy from SOBotics I guess), you'll see this if you want to do a failover from MS:

![selection_152](https://cloud.githubusercontent.com/assets/12422882/23296582/c4a869aa-fa9b-11e6-811a-00634a97c860.png)

As most bots don't have a web dashboard, I guess we can implement this in a command if needed.

**Comment by FelixSFD** [comment]
We could implement this independently from the bot's own dashboard. A dashboard that has the single purpose to monitor all bots and organize, which instance is active. This dashboard could also show statistics (for example remaining quota) like on metasmoke.

**Comment by Undo1** [comment]
It'd be easy to write a quick Rails app to manage multiple types of bots and send failover commands.

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-3).

Simple answer: Yes, we do want to run backup instances. Possible approach: monitor if the bots are alive through a consistent command, and fallback on other instances if they're dead.

**Comment by Undo1** [comment]
To clarify for future readers, that's "Yes, we *do* want..."

**Comment by Tunaki** [comment]
Ups, just edited that, thanks @Undo1 !
