### ISSUE TITLE
Do we need more work force for development?

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOCVFinder/SOCVFinder.github.io#12]
There are community promo ads that will soon be started for this year on MSO. That would be useful if we need more users to take part. 

Do we need to advertise on that? 

If yes, we will need to create a /contribute page.

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-1).

Let's not preclude doing ads, but remember that they need to be done well to be effective, so it's probably worth letting other room people critique your work before you go live.

Ideas for ads will be collected in an issue on GH during the next weeks.
