### ISSUE TITLE
Are there too many bot messages in the room?

### ISSUE THREAD

**Issue by Tunaki** [SOCVFinder/SOCVFinder.github.io#2]
When introducing the room to new users, that are eager to build incredible things and lovely bots, they can be taken aback by the (huge) number of messages posted by bots in the room, at any time.

Should this be reduced, or do we consider it okay?

**Comment by jdd-software** [comment]
We are closing in on the limit but the room as I see it will always be a room with lot of bot messages and not much chatting (SOCVR is a chat room, SOBotics backstage working room). What we should strive for is bring the bot's to other rooms if possibile (hence by tag on question) and then keep our high load of bot messages that change's depending on what we are testing. For example if someone like to test something new SOFun can shut up... etc.  The production bot's SOCVFinder, HeatDetector, Firealarm are not generating many messages, just Natty but it's also one of our most useful bots, flagging answers works well on SO not like flagging questions, maybe natty can change the message to take up less space (we click to question anyway)

**Comment by Bhargav-Rao** [comment]
I'm all in for reducing the length of Natty's post. I'm thinking of editing the post before 2 mins, But that'd put a lot of load. (At peak time we get 3 answers per minute). 

At the moment GMTs report looks like this:

http://chat.stackoverflow.com/transcript/75819?m=35732300#35732300

Can we change it to that?

**Comment by jdd-software** [comment]
seems nice to me, whatever is quick for you, we basically need link to sentinel, link to question other info as score, user is optional. I would however pass a new message with link to comment if Natty pass one. The days of testing Natty is gone, full production now which means we visit all answers anyway.

**Comment by Floern** [comment]
I like Natty's report format as it is now, although the post preview (i.e. "Body Starts With:") could be trimmed down to max ~5 words. Some reports contain 2 lines of the preview, which is too much and unnecessary. The autoflag info could be included into the report like in GMT's. Also why does the report contain the question [tag]? That's imho useless.

**Comment by Bhargav-Rao** [comment]
The tag serves a hidden purpose, @Floern. The reason why it exists is for expansion. When we expanded to the R moderation room, we could clearly inform them that there are ~3 posts per day on an average.

**Comment by FelixSFD** [comment]
The GMT reports look well. I think we could use them depending on the location set in the properties: When Natty runs on the server, use the short message and when it runs somewhere else, use the old one for debugging purposes

**Comment by Tunaki** [comment]
+1 on the format of the report in GMT @Bhargav-Rao. Very clean.

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-7), shared with #4.

Everything is fine, maybe a small tweak here and there. If you're looking for a bot-free room, this is probably the wrong place. 
The number of bots is irrelevant, but we have to watch out that we don't drown in messages, so just make sure the bots don't spam the room.
