### ISSUE TITLE
Discuss the future of Sockite

### ISSUE THREAD

**Issue by Papershine** [SOCVFinder/SOCVFinder.github.io#20]
As discussed at https://github.com/SOBotics/SOBotics.github.io/issues/17, some people (including me) now have second thoughts about creating a bot for voting fraud/sockpuppeting, while [some](https://chat.stackoverflow.com/transcript/message/41713407#41713407) think that probably it's still good to go. This topic is to talk about **whether the development of Sockite should continue**.

Reasons for why Sockite should be continued:

 - Data could be presented differently, for example, make a web dashboard which requires privileges to view reports to prevent a witch hunt from going on
 - Sockite could be placed into the moderator-only room MOBotics, where only moderators can interact with the reports <sup>[citation needed]</sup>

Reasons for why Sockite should not be continued:

 - It could be used for a witch hunt tool and some people may have some false conclusions from the data posted
 - Magisch's query is already pretty accurate in detecting voting fraud
 - We are not sure of the accuracy of the bot

Currently, the filters are to be implemented (and can be implemented possibly with the API) can be found [here](https://github.com/SOBotics/Sockite/issues/1). IIRC, Magisch's query is quite accurate because of a loophole in SEDE, so Sockite might not be able to produce the same amount of accuracy (?).

**Comment by double-fault** [comment]
Are you going to keep the source private or public?

If you're keeping it public, someone can just modify it with few lines of code to make it post in chat.

 If you're keeping it private, some users may object to using a tool without proper disclosure. Would you be posting something on meta disclosing this?

**Comment by Papershine** [comment]
@Fortunate-MAN It's a hard choice, but public source would be better for me. Firstly, there would not be any instructions on installing and how to install it. Secondly, why would a user want to waste some time to understand the whole codebase and edit it just to chase users? We could license it under GPL to require people to release their edited source. If we see it, we can try contact them. Thirdly, a moderator-only bot, [UserStalker](https://github.com/SOBotics/UserStalker), is open source. Also FWIW it seems that the chance of someone doing this just to see some reports about possible voting fraud is very very slim.

**Comment by double-fault** [comment]
What are you going to do to disclose this (if it works and is actively used) to the community? A meta post?

IMO, things like fraud, autoflagging etc are sensitive topics, and disclosure is important otherwise the community could label us as a group of people who flag purely based on a bot.

**Comment by Papershine** [comment]
@Fortunate-MAN If it was included in MOBotics, I think we should ask the opinions of the mods there if they want to open a meta post, but if it was reported to public chat/a web dash, after rigid testing and filter improvements, I would make a meta post and see the response of the community.

**Comment by Bhargav-Rao** [comment]
https://chat.stackoverflow.com/rooms/167761/conversation/2018-03-sobotics-room-meeting-topic-5

- It was decided that we let the bot development work continue. 
- While testing the bot, the bot can be in a public room, but on completion of testing, the bot must be moved to a private room.
