### ISSUE TITLE
How should security vulnerabilities be handled?

### ISSUE THREAD

**Issue by double-fault** [SOCVFinder/SOCVFinder.github.io#21]
If a bot leaks private credentials, or if some US or any other piece of software has a security vulnerability, how should this be handled? 

 - Is there any official guideline for this? If not, what should be done?
 - Should the software be immediately taken down as a precaution?
 - What all can be classified as a security vulnerability? Would a leaked SE api key or a Redunda key be a problem?

**Comment by Bhargav-Rao** [comment]
https://chat.stackoverflow.com/rooms/167761/conversation/2018-03-sobotics-room-meeting-topic-6

-  It was decided that high risk vulnerabilities be mailed to contact@sobotics.org
- The website would be edited to indicate this.
