### ISSUE TITLE
Should future room meetings be handled in a different way?

### ISSUE THREAD

**Issue by double-fault** [SOCVFinder/SOCVFinder.github.io#22]
I've noticed that usually room meetings are held in a periodic fashion. This means that when an issue comes up which concerns the whole room and no meeting is close, it's usually just discussed in chat, and few users miss out. This also means that there will be no official consensus posted.

Should we have users post an issue on GH whenever they come across an issue, and when a number of issues gather up, a room meeting should be called? Or is a periodic fashion more appropriate? Should we just dispose of room meetings completely, as not all users in different timezones are able to attend these and just post these issues on GH where everyone should post their opinions?

**Comment by Bhargav-Rao** [comment]
https://chat.stackoverflow.com/rooms/167761/conversation/2018-03-sobotics-room-meeting-topic-7

- It was decided that the present structure of room meetings are fine, given that they are held annually. 
- The time of the meeting might have to be changed, but that would be discussed while we are planning a new meeting.
