### ISSUE TITLE
Should Channels eventually be opened to all users?

### ISSUE THREAD

**Issue by double-fault** [SOCVFinder/SOCVFinder.github.io#23]
Channels, currently only restricted to `@sobotics.org` email account holders, could be opened to all users. 

Should we do this? Will doing this actually have an advantage or would it just increase the complexity of moderating Channels, and possibly dealing with trolls and spam?

**Comment by Bhargav-Rao** [comment]
How do you propose to "open" channels to all user? Utilizing non organization emails is heavily frowned upon and the channel admins have been instructed not to use that.

**Comment by double-fault** [comment]
@Bhargav-Rao I'd seen a few messages a time ago about utilizing non-organization emails in SOBotics; I didn't know you were instructed not to do that.

Seems like this is a pretty useless topic then, closing.

**Comment by Bhargav-Rao** [comment]
Well, Let us not forget that we have got access to Channels just for the alpha testing. Once they're done with that, we're all out. They probably will provide us with a tar ball with the XML of every post.

**Comment by ArtOfCode-** [comment]
It's possible to do this how Charcoal does it - use AWS to catch incoming emails from a domain and redirect the join links to chat
