### ISSUE TITLE
SOFun

### ISSUE THREAD

**Issue by jdd-software** [SOCVFinder/SOCVFinder.github.io#3]
I have started to feed all posts that probably should be closed, mostly just to see the quantity. I know we can't handle all thezzz stuff, my basic idea is to move the feed to another room, to maybe show people the mess we have on SO (arise awareness)

**Comment by Tunaki** [comment]
I think the load is just fine for now.

**Comment by FelixSFD** [comment]
We could bundle the possible bad questions to reports every 5-10 minutes:

http://chat.stackoverflow.com/transcript/111347?m=35735441#35735441

The report could be a simple HTML table somewhere
