### ISSUE TITLE
Migrating bots to not use OpenID

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOCVFinder/SOCVFinder.github.io#30]
These are the list of bots present at Sobotics which need to be migrated within July 25th. 

At Sobotics:

- [x] SOCVFinder & HeatDetector
- [x] FireAlarm
- [x] Burnaki 
- [x] Natty
- [x] Badger
- [x] Guttenberg
- [x] Generic Bot
- [x] Belisarius
- [x] Tag Wiki Edit Monitor
- [x] CheckYerFlags
- [x] Open Reports
- [x] Notepad
- [x] Juker
- [x] Thunder
- [x] Pham

Guest bots:

- [x] SmokeDetector
- [x] Edit Monitor

At Workshop

- [x] SoundFlow
- [x] ChatCradle
- [x] Sockite
- [x] Boson

At SEBotics

- [x] CitationDetector

At Mobotics:

 - [x] User Stalker

**Comment by NobodyNada** [comment]
I've opened a [ChatExchange PR](https://github.com/Manishearth/ChatExchange/pull/152) to replace the deprecated OpenID login.

**Comment by Bhargav-Rao** [comment]
Thanks for that @NobodyNada, it was just the Python Bots which had to be moved. 

That leaves us with SOCVFinder, which Petter will do this week end, and Burnaki which we probably would need to poke GoogleNoob to fix it.

**Comment by FelixSFD** [comment]
@Bhargav-Rao The currently running version of Burnaki is using the new version: https://chat.stackoverflow.com/transcript/message/43219929#43219929

**Comment by Bhargav-Rao** [comment]
@FelixSFD Yep, which is why I mentioned that we need to poke him to push the changes onto another branch of Burnaki. Probably set up a locked master and the default development branches and ask him to push to the dev one?

**Comment by Filnor** [comment]
Both SoundFlow and CheckYerFlags ran without OpenID for some time now, but I just updated ChatCradle. Now all of my bots are using the new login, so you can tick them of for me (can't edit due to missing rights).

**Comment by Filnor** [comment]
It seems that both of the remaining bots, Thunder and Smokey, have been updated. Therefore we can tick them of and close this issue.
