### ISSUE TITLE
SOCVFinder - find questions to close (and dupe feed)

### ISSUE THREAD

**Issue by jdd-software** [SOCVFinder/SOCVFinder.github.io#5]
Mostly running in background a possibile development could be to search for del votes, I have not pushed this since I find that Magic Review is working nicely, do we feel the need?

Rene had also shown interest to run it on meta?, What do you think

**Comment by Tunaki** [comment]
[MagicTagReview](https://github.com/Tiny-Giant/myuserscripts/blob/master/MagicTagReview.user.js) is really nice yes. But it's true that integrated in chat, with a nice report _à la Sam (wink wink) :)_ would be even better! It could contain a list of questions with pending delete votes, sorted by votes descendingly. Search would be by tag / score.

**Comment by double-fault** [comment]
This batching feature of SOCVFinder also reminds me if it would be useful for FireAlarm to have a command which would print all reports below a specific threshold specified in the command (lower threshold means better chance of being closed) which have cv's but are not closed? This is pretty much like SOCVFinder, but the difference is that SOCVFinder cannot classify posts based on their content, but instead only on cv's. FireAlarm can classify post on their content, and thus it can feed you the _worst_ questions from its earlier reports too.

**Comment by jdd-software** [comment]
@Fortunate-MAN The reports runs on Sam's server it's enough to send a json to get one generated, so the implementation would not be to time consuming

**Comment by Bhargav-Rao** [comment]
Now that we have changed the room name, should we rename "SOCV Reports" that come up on all the SOCVFinder batches?

**Comment by jdd-software** [comment]
it says SOCVR Reports, Sam made it, since at that time we where pretty much developing queen to be able to run in SOCVR, not sure we could ask him to change to SOBotics Report, but meehhh,

**Comment by ArcticEcho** [comment]
(Sorry for bumping an old issue, only just noticed I was mentioned here.)

I'm going to be "renovating" the API next week so Tuna's bot has a proper endpoint/params to use rather than leeching off Queen's. I'd be happy to add support for the tag review script too.

**Comment by Bhargav-Rao** [comment]
@ArcticEcho It would be best if you make a generic API. One of questions, one for answers and one for posts. In this way even FireAlarm, Natty, etc can call the API and get a nice report.

**Comment by ArcticEcho** [comment]
+1 Great idea, I'll do that instead.

I'll probably have to wait for the socvr.org domain transfer to complete before working on the API though.

**Comment by NobodyNada** [comment]
We can (and have been planning on) make this API part of Redunda

**Comment by ArcticEcho** [comment]
Oh ok, so I'll leave this with you guys then?

**Comment by jdd-software** [comment]
@NobodyNada similar as current report?

**Comment by NobodyNada** [comment]
@jdd-software Huh?  I'm not sure what you mean, sorry.

**Comment by Bhargav-Rao** [comment]
@NobodyNada I guess petter wanted to ask if the reports from the API which you are planning to make, would be similar to the present reports of Queen. If not, then @ArcticEcho will have to work on creating the answer reports  API.

**Comment by jdd-software** [comment]
Yeah, sorry missed the comment, if you are starting from Sam's report, hence similar structure and layout or planning something else.

**Comment by NobodyNada** [comment]
@jdd-software @ArcticEcho I'm sorry; I think I got confused here.  We're thinking about making APIs that allow bots to access questions( answers, etc. from Redunda, but I don't think we've been planning on any reports functionality.  Might be worth having a discussion in the Redunda chat room though.
