### ISSUE TITLE
Heat detector - comments feed

### ISSUE THREAD

**Issue by jdd-software** [SOCVFinder/SOCVFinder.github.io#7]
I have left this as it was when NATO (Natty project) started. 

It needs to evaluate
1. Scoring, regex vs classifiers.
2. Classifiers need to be update with new bad and good comments (I have around 1000 already classified but need to take a quick look and  16.000 not classified)

My basic idea was to make a 
bad regex filter --> notification
regex + naive bayes (update feed) --> notification

The main problem is the heavy work load of classifying comments to create the feeds, specially since in the beginning we where much more hard, hence any nc comment was bad, with time we let more comments slip by, so maybe it would be good to check the whole comment feed... but arrgh... that's a lot of work.

**Comment by Tunaki** [comment]
I left this awesome project a bit, but yeah we definitely need to get back to it. If we need to have (long) sessions of manual reviews, I'm in.

**Comment by double-fault** [comment]
I'm in too if we have to manually review comments whether they are rude or not rude. But do note that I won't be available for much time on Weekdays.
