### ISSUE TITLE
SOReviewers

### ISSUE THREAD

**Issue by jdd-software** [SOCVFinder/SOCVFinder.github.io#8]
I removed the feed, is somebody missing it?, what is Floern up to?

**Comment by Tunaki** [comment]
Disabled as long as it's spamming lots of dupe chat messages is OK for me. When this is resolved, I could see the bot notify disputed reviews for example, or things that are deleted but with 2 Looks OK (and conversely, things that are deemed OK but with lots of Recommend Deletion vote), etc.

**Comment by Bhargav-Rao** [comment]
Unless the API adds review data, we can't do it. Else we need to screen scrape every 30 mins. We can speak to a CM and ask their permission.

**Comment by jdd-software** [comment]
To me reporting comments is not the right way if we like to find all the interesting stuff, it was a quick hack to find some of what people was doing (+ have links to actually review), it could be used to find bad reviewers, delete answers faster (enter review) and to report tn to natty. We need to have a goal what we like to do, then find the best solution. Everyone of those single task would have it particular implementation.

**Comment by Floern** [comment]
Missing the comments? Not really.

Getting the review data is still on my todo list. I don't think scraping the review history is a big deal, that would be one request every 30 minutes or 1 hour depending on the queue. If I'd do that under my account, it probably would increase my impact on the SO servers by 1%..

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-5).

The current sub-optimal system will be left shut off, and a new project is under way, that will have to make use of limited, controlled 10k+ screen scraping.
