### ISSUE TITLE
Guttenberg - More sources to compare the targets with

### ISSUE THREAD

**Issue by FelixSFD** [SOCVFinder/SOCVFinder.github.io#9]
Since I've launched Guttenberg, we made lots of improvements to the algorithm that compares two posts. But since day one, we only have two sources for answers that are compared with the "target" posts: The _linked_ and _related_ questions

Whilst this sometimes returns good results, Guttenberg misses some really obvious matches: http://chat.stackoverflow.com/transcript/message/35789089#35789089

Are there any other sources, Guttenberg could query every minute? (SO's search won't work)

**Comment by jdd-software** [comment]
There is the bing/google search but as we know we could only do a few search everyday, maybe if we come up with a strategy when to search?, hence when is a post possibile plag, if it fits search bing..

**Comment by FelixSFD** [comment]
This free API could work: http://www.faroo.com/hp/api/api.html#description

But I don't know, if Guttenberg would need to many requests

**Comment by Bhargav-Rao** [comment]
@FelixSFD  http://chat.stackoverflow.com/search?q=faroo&room=111347

**Comment by Tunaki** [comment]
What about GitHub Search API? https://developer.github.com/v3/search/
> you can make up to 30 requests per minute

**Comment by jdd-software** [comment]
Yeah I tested some search on faroo, the main problem I found was that the search result where not good. Github seems like a more promising solution.

**Comment by FelixSFD** [comment]
The GitHub search sounds great! Are there any restrictions, how long `q` can be? If yes, it could be hard to decide, which part of the code will be used for the query

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-4).

Yes, more sources would be good but we need more research. For now: possibilities are GitHub search API, and SO data dump.
